{% set name = "fpm" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}.F90
  url: https://github.com/fortran-lang/fpm/archive/0faa0021cdc5d8ad15d9693e9ce27f7b2fb196ac.tar.gz
  sha256: 609c3da0ea86a969e9bc3001598fd1e15efb7ec18e6d2684f6e7276290111481
  patches:
    - 01-opendir-osx-arm.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - fpm  # [build_platform != target_platform]
    - curl  # [build_platform == target_platform]
  host:
    - llvm-openmp  # [osx]
    - libgomp  # [linux and not aarch64]


test:
  commands:
    - fpm --version

about:
  home: https://github.com/fortran-lang/fpm
  license: MIT
  license_family: MIT
  license_file:
    - "LICENSE"
    - "LICENSE-MIT.toml-f"
    - "LICENSE-Apache.toml-f"
    - "LICENSE.M_CLI2"
  summary: "Fortran package manager"
  doc_url: https://fpm.fortran-lang.org
  dev_url: https://github.com/fortran-lang/fpm

extra:
  recipe-maintainers:
    - awvwgk
    - certik
