{% set name = "fpm" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}.F90
    sha256: 48e563db74af6b9396ebe4a67bd371210e2ea8c6e2b3cc230e68183ce7509422
    fn: fpm.F90
    folder: build/bootstrap
  - url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}.zip
    sha256: 00d687e17bdada4dcae0ff1ea2e01bad287dcc77a74c3bbde0c9ff9633b655bb

build:
  number: 1

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]


test:
  commands:
    - fpm --version

about:
  home: https://github.com/fortran-lang/fpm
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE-MIT.toml-f
    - LICENSE-Apache.toml-f
    - LICENSE.M_CLI2
  summary: Fortran package manager
  doc_url: https://fpm.fortran-lang.org
  dev_url: https://github.com/fortran-lang/fpm

extra:
  recipe-maintainers:
    - awvwgk
    - certik
