{% set name = "fpm" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}.F90  # [unix]
    sha256: 0c95309f365a40900108f3325e17e99a0456ce76046c37326349bf61b3df447a  # [unix]
    fn: fpm.F90  # [unix]
    folder: build/bootstrap  # [unix]
  - url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}.zip  # [unix]
    sha256: 67fd8f4f78d19662c61855f531465e347ab0bc913ba59bd419f75f4022d2cd70  # [unix]
  - url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}-windows-x86_64.exe  # [win]
    sha256: 1fac1b8338e6ce7ee8e0b57f8c35fb21c99788c8c525d04163f506e5d3a2d3ab  # [win]
    fn: fpm.exe  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - llvm-openmp  # [osx]
    - libgomp  # [linux]


test:
  commands:
    - fpm --version

about:
  home: https://github.com/fortran-lang/fpm
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE-MIT.toml-f
    - LICENSE-Apache.toml-f
    - LICENSE.M_CLI2
  summary: Fortran package manager
  doc_url: https://fpm.fortran-lang.org
  dev_url: https://github.com/fortran-lang/fpm

extra:
  recipe-maintainers:
    - awvwgk
    - certik
