{% set name = "fpm" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}.F90
    sha256: 988a3317ee2448ee7207d0a29410f08a79c86bddac3314b2a175801a9cf58d27
    fn: fpm.F90
    patches:   # [win]
      - resp.patch  # [win]
    folder: build/bootstrap
  - url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}.zip
    sha256: f6c998c9afd39eb42c7e80a306cfbed5faa77eaa42eb4f75b93864c338db1795

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ stdlib('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ stdlib('m2w64_c') }}  # [win]
    - llvm-openmp  # [osx]
    - libgomp  # [linux]


test:
  commands:
    - fpm --version

about:
  home: https://github.com/fortran-lang/fpm
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE-MIT.toml-f
    - LICENSE-Apache.toml-f
    - LICENSE.M_CLI2
  summary: Fortran package manager
  doc_url: https://fpm.fortran-lang.org
  dev_url: https://github.com/fortran-lang/fpm

extra:
  recipe-maintainers:
    - awvwgk
    - certik
