{% set name = "fpm" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}.F90  # [unix]
    sha256: 17a809d512618ddb083b1d8c546a2d98e704b10484f607df7b0b231ddc8ff277  # [unix]
    fn: fpm.F90  # [unix]
    folder: build/bootstrap  # [unix]
  - url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}.zip  # [unix]
    sha256: 365516f66b116a112746af043e8eccb3d854d6feb1fad0507c570433dacbf7be  # [unix]
  - url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}-windows-x86_64.exe  # [win]
    sha256: 51643e74ebeb3e2222d8a21abf3a9eea87a56f09c2ac67137d6a41ac851fa7a0  # [win]
    fn: fpm.exe  # [win]

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - llvm-openmp  # [osx]
    - libgomp  # [linux]


test:
  commands:
    - fpm --version

about:
  home: https://github.com/fortran-lang/fpm
  license: MIT
  license_family: MIT
  license_file:
    - "LICENSE"
    - "LICENSE-MIT.toml-f"
    - "LICENSE-Apache.toml-f"
    - "LICENSE.M_CLI2"
  summary: "Fortran package manager"
  doc_url: https://fpm.fortran-lang.org
  dev_url: https://github.com/fortran-lang/fpm

extra:
  recipe-maintainers:
    - awvwgk
    - certik
