{% set name = "fpm" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}.F90
  sha256: a0670253a27a8b3745e694279d1c5feacbb111a932537c5932edde0c0f3ffa8b

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
  host:
    - llvm-openmp  # [osx]
    - libgomp  # [linux and not aarch64]


test:
  commands:
    - fpm --version

about:
  home: https://github.com/fortran-lang/fpm
  license: MIT
  license_family: MIT
  license_file:
    - "LICENSE"
    - "LICENSE-MIT.toml-f"
    - "LICENSE-Apache.toml-f"
    - "LICENSE.M_CLI2"
  summary: "Fortran package manager"
  doc_url: https://fpm.fortran-lang.org
  dev_url: https://github.com/fortran-lang/fpm

extra:
  recipe-maintainers:
    - awvwgk
    - certik
