{% set name = "fpm" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}.F90  # [unix]
    sha256: 556b3883ba1db6fd62c99ba7143f1e97ebb409729c4209f03aa3c6fc970cce3f  # [unix]
    fn: fpm.F90  # [unix]
    folder: build/bootstrap  # [unix]
  - url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}.zip  # [unix]
    sha256: 484debabd7d22186ac41f865ddf63475c279a61a51aaff5636ed615860b5b8d7  # [unix]
  - url: https://github.com/fortran-lang/fpm/releases/download/v{{ version }}/fpm-{{ version }}-windows-x86_64.exe  # [win]
    sha256: 66fdfe741837ecf257e17ed4308e911cc85ac448b7f15994c84bbd6cb2cef220  # [win]
    fn: fpm.exe  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - llvm-openmp  # [osx]
    - libgomp  # [linux]


test:
  commands:
    - fpm --version

about:
  home: https://github.com/fortran-lang/fpm
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE-MIT.toml-f
    - LICENSE-Apache.toml-f
    - LICENSE.M_CLI2
  summary: Fortran package manager
  doc_url: https://fpm.fortran-lang.org
  dev_url: https://github.com/fortran-lang/fpm

extra:
  recipe-maintainers:
    - awvwgk
    - certik
