conda_forge_output_validation: true
test_on_native_only: true
build_platform:
  osx_arm64: osx_64
provider:
  linux_ppc64le: default
  linux_aarch64: default
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
